sudo: required
language: php
dist: trusty

php:
  - 7.1
  - 7.2

branches:
  except:
    - /^analysis-/

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

before_script:
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  - composer install --prefer-dist --ignore-platform-reqs
  - nvm install node
  - npm install -g yarn
  - yarn
  - yarn run dev -- --progress=false
  # - cp .env.dusk .env
  # - ./vendor/laravel/dusk/bin/chromedriver-linux &
  # - php artisan serve &

script:
 - ./vendor/bin/phpunit
 # - php artisan dusk
